# -*- coding: utf-8 -*-
"""CLASE_8_8SEPTIEMBRE2022 JUAN DAVID FONSECA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O4xQS0uYgc5n7VEPR5cVQlhvGztYXglL

<center>


#**COLEGIO SIGLO - EL SOCORRO**
#**PRESENTADO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR:JUAN DAVID FONSECA**
#**GRADO DÉCIMO**
#**8 SEPTIEMBRE 2022**

#**¿QUE ES PYTHON?**
# Python es un lenguaje de alto nivel de programación interpretado cuya filosofía hace hincapié en la legibilidad de su código, se utiliza para desarrollar aplicaciones de todo tipo, ejemplos: Instagram, Netflix, Spotify, Panda 3D, entre otros

#**LANZAMIENTO:** 1991
#**CREADO POR:** Guido van Rossum
#**RECUPERADO DE:**https://www.redalyc.org/pdf/1815/181531232001.pdf
"""

print("esto es una suma")
numero_uno=3.14159265
numero_dos=3.14159265
resultado = numero_uno + numero_dos
print(resultado)

print("esto es una resta" )
numero_uno=3.14159265
numero_dos=3.141592651
resultado = numero_uno - numero_dos
print(resultado)

print("esto es una multiplicacion")
numero_uno=1231231231231231.88888
numero_dos=3214672136478264723784623746782
resultado = numero_uno * numero_dos
print(resultado)

print("esto es una division")
numero_uno=72643721364782364876478623784672836478263874623784672346872364782364876238
numero_dos=204782374982374897123984723894721837458934754809237491823748237482734896723
resultado = numero_uno / numero_dos
print(resultado)

"""#Ejercicio de tipos de datos simples

## Ejercicio 1

Escribir un programa que pregunte el nombre del usuario en la consola y un numero entero e impreima por pantalla  en lineas distintas el nombre del usuario tantas veces como el numero introducido
"""

nombre = input("¿cómo te llamas?")
n = input("introduce un número entero: ")
print((nombre + "\n") *int(n))

"""
## EJERCICIO 2

Escribir un programa que pida al usuario su peso (en KG) y estatura (en M),
calcule el indice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'tu indice de masa corporal es <imc>' donde  '<imc>' es el indice de masa corporal calculado redondeado con dos decimales 
"""

peso = input("¿cual es tu peso en KG?")
estatura = input("¿cual es tu estatura en M?")
imc = round(float(peso)/float(estatura)**2,2)
print("tu indice de masa corporal es " + str(imc))

"""## **LÍBRERIAS EN PHYTON**
# ¿Que es?:
# #En este sentido, una librería es un conjunto de archivos que se utiliza para desarrollar software. Suele estar compuesta de código y datos, y su fin es ser utilizada por otros programas de forma totalmente autónoma. Simple y llanamente, es un archivo importable.
"""